version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install psycopg2-binary -t .
  build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputtemplate.yaml